# Generated by Django 2.2.7 on 2019-12-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loopstudy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
    ]
