# Generated by Django 2.2.7 on 2019-12-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loopstudy', '0003_ciclo_dono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciclo',
            name='tamanho',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
